// vui-design/components/spin/index.jsx
import withInstall from "../../utils/withInstall";
import VuiSpin from "./src/spin";
import Popup from "../../libs/popup";
import is from "../../utils/is";

/**
* 默认配置
*/
const defaults = {
  size: "large",
  animation: "vui-spin-fade",
  getPopupContainer: () => document.body
};

/**
* 创建 Spin 实例
* @param {Object} options 
*/
const createSpinInstance = options => {
  // 创建 Spin 挂载的 html 根节点
  const container = options.getPopupContainer();
  const el = document.createElement("div");

  container.appendChild(el);

  delete options.getPopupContainer;

  // 创建 Spin 实例
  const component = {
    el,
    components: {
      VuiSpin
    },
    data() {
      const state = {
        ...options,
        visible: false
      };

      return {
        state
      };
    },
    methods: {
      spinning() {
        this.state.visible = true;
      },
      cancel() {
        this.state.visible = false;
      },
      handleAfterLeave() {
        this.$destroy();
        this.$el && this.$el.parentNode && this.$el.parentNode.removeChild(this.$el);
      }
    },
    render(h) {
      const { state, handleAfterLeave } = this;

      if (!state.visible) {
        return;
      }

      const attributes = {
        props: {
          fullscreen: true,
          size: state.size,
          delay: state.delay,
          indicator: state.indicator,
          message: state.message
        },
        style: {
          zIndex: Popup.nextZIndex(),
          background: state.background
        }
      };

      return (
        <transition appear name={state.animation} onAfterLeave={handleAfterLeave}>
          <VuiSpin {...attributes} />
        </transition>
      );
    }
  };

  return new Vue(component);
};

/**
* 对外提供 spinning 接口
* @param {String/Object} options 
*/
VuiSpin.spinning = function(options = {}) {
  if (is.server) {
    return;
  }

  if (!is.string(options) && !is.json(options)) {
    return;
  }

  if (is.string(options)) {
    options = {
      message: options
    };
  }

  options = {
    ...defaults,
    ...options
  };

  const instance = createSpinInstance(options);

  instance.spinning();

  return instance;
};

/**
* 对外提供 install 接口，用于全局注册
* @param {Function} Vue 
*/
export default withInstall(VuiSpin);

// vui-design/components/spin/index.tsx
import type { App, AppContext, Plugin, PropType } from "vue";
import type { SpinWrapperProps, Size, Indicator } from "./types";
import { createVNode, render, defineComponent, ref, onBeforeMount } from 'vue';
import Spin from "./spin";
import usePopupManager from "../../hooks/usePopupManager";
import is from "../../utils/is";
import { sizes } from "./constants";

const createSpinInstance = (properties: SpinWrapperProps, appContext?: AppContext) => {
  const { getPopupContainer, ...props } = properties;
  const apis: Record<string, any> = {};
  const container = is.function(getPopupContainer) ? getPopupContainer() : document.body;
  const component = defineComponent({
    name: "vui-spin-wapper",
    props: {
      visible: {
        type: Boolean as PropType<boolean>,
        default: true
      },
      size: {
        type: String as PropType<Size>,
        validator: (size: Size) => sizes.includes(size),
        default: "large"
      },
      background: {
        type: String as PropType<string>,
        default: undefined
      },
      delay: {
        type: Number as PropType<number>,
        default: undefined
      },
      indicator: {
        type: Function as PropType<Indicator>,
        default: undefined
      },
      message: {
        type: String as PropType<string>,
        default: undefined
      },
      animation: {
        type: String as PropType<string>,
        default: "vui-spin-fade"
      }
    },
    setup(props) {
      const visible = ref(props.visible);
      const size = ref(props.size);
      const background = ref(props.background);
      const delay = ref(props.delay);
      const indicator = ref(props.indicator);
      const message = ref(props.message);
      const animation = ref(props.animation);

      const { zIndex } = usePopupManager("popup", { visible });

      const update = (next: SpinWrapperProps) => {
        if (!is.string(next) && !is.object(next)) {
          return;
        }

        if (is.string(next)) {
          next = {
            message: next
          };
        }

        if (is.boolean(next.visible)) {
          visible.value = next.visible;
        }

        if (is.string(next.size)) {
          size.value = next.size;
        }

        if (is.string(next.background)) {
          background.value = next.background;
        }

        if (is.number(next.delay)) {
          delay.value = next.delay;
        }

        if (is.function(next.indicator)) {
          indicator.value = next.indicator;
        }

        if (is.string(next.message)) {
          message.value = next.message;
        }

        if (is.string(next.animation)) {
          animation.value = next.animation;
        }
      };

      const cancel = () => {
        visible.value = false;
      };

      const handleOpen = () => {

      };

      const handleClose = () => {
        render(null, container);
      };

      onBeforeMount(() => {
        apis.update = update;
        apis.cancel = cancel;
      });

      return () => {
        const attributes = {
          visible: visible.value,
          fullscreen: true,
          size: size.value,
          delay: delay.value,
          indicator: indicator.value,
          message: message.value,
          animation: animation.value,
          style: {
            zIndex: zIndex.value,
            background: background.value
          },
          onOpen: handleOpen,
          onClose: handleClose
        };

        return (
          <Spin {...attributes} />
        );
      };
    }
  });

  const vm = createVNode(component, props);

  vm.appContext = appContext ?? vm.appContext;

  render(vm, container);

  return apis;
};

Spin.spinning = function(config: string | SpinWrapperProps = "", appContext?: AppContext) {
  if (is.server) {
    return;
  }

  if (!is.string(config) && !is.object(config)) {
    return;
  }

  if (is.string(config)) {
    config = {
      message: config
    };
  }

  return createSpinInstance(config, appContext);
};

Spin.install = function(app: App) {
  app.component(Spin.name, Spin);
  app.config.globalProperties.$spin = Spin;

  return app;
};

export type { SpinProps } from "./spin";

export { createProps as createSpinProps } from "./spin";

export default Spin as typeof Spin & Plugin;
